#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################

language: java

sudo: required

dist: trusty

before_install: ### TODO: remove - debug step
  - sudo apt-get update -qq
  - sudo apt-get install -y sshpass

env:
 global:
   - JAVA_OPTS="-XX:MaxPermSize=512m"
 matrix:
   - SUITE=containers
   - SUITE=images
   - SUITE=docker-misc
   - SUITE=git


script:
  - docker run --privileged -d -p 4444 -p 49153:22 -e PORT=4444 --name docker_host_ssh orius123/dind-ssh
  - docker logs docker_host_ssh ### TODO: remove -- debug step
  - ls -l # sshpass -p screencast ssh -p 49153 root@localhost pwd ### TODO: remove - debug step
  - sleep 10 ### configuration time for dind conatainer
  - docker logs docker_host_ssh ### TODO: remove - debug step
  - ls -l # sshpass -p screencast ssh -p 49153 root@localhost pwd ### TODO: remove - debug step
  - docker ps -a ### TODO: remove - debug step
  - docker info
  - docker version
  - df -kh
  - wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.8.0/cslang-builder.zip
  - unzip -q cslang-builder.zip -d cslang-builder
  - chmod +x cslang-builder/bin/cslang-builder
  - ./cslang-builder/bin/cslang-builder -ts ${SUITE},\!default -cov
    
# cat prints only part of the file for some reason so we print ourselves
after_failure: while read line; do printf "%s\n" "$line"; done < builder.log
