#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################

language: java

sudo: required

services:
  - docker

env:
 global:
   - JAVA_OPTS="-XX:MaxPermSize=512m"
 matrix:
   - SUITE=containers
   - SUITE=images
   - SUITE=docker-misc,docker_examples
   - SUITE=git,remote-copy

script:
    - git fetch origin
    - git branch -a
#    - git checkout master || git checkout -b master origin/master
    - git diff --name-only origin/master -- > difflist.txt
    - cat difflist.txt
    - grep '.sl$' difflist.txt > changed_items.txt
    - sed -i -e 's/\//\./g' changed_items.txt
    - sed -i -e 's/test\.//g' changed_items.txt
    - sed -i -e 's/content\.//g' changed_items.txt
    - sed -i -e 's/\.sl//g' changed_items.txt
    - cat changed_items.txt

# cat prints only part of the file for some reason so we print ourselves
after_failure: while read line; do printf "%s\n" "$line"; done < ./cslang-builder/logs/builder.log
