language: java
script:
  - wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.7.14/cslang-builder.zip
  - unzip cslang-builder.zip -d cslang-builder
  - chmod +x cslang-builder/bin/cslang-builder
  - ./cslang-builder/bin/cslang-builder ./content
