I#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################

language: java

addons:
  artifacts:
    paths:
    - $HOME/builder.log
  
sudo: true

env:
 global:
   - UML_DOCKERCOMPOSE=0
   - UML_FIG=0
   - JAVA_OPTS="-XX:MaxPermSize=512m"
   - BRANCH=develop 
   - DOCKER_BACKEND_FS=host  
   - DOCKER_STORAGE_DRIVER=devicemapper --storage-opt dm.override_udev_sync_check=true
  # - QUIET=1
 matrix:
   - SUITE=containers
   - SUITE=images
   - SUITE=docker-misc
   
install:
  - sudo apt-get update
  - sudo apt-get install -y linux-image-virtual linux-image-extra-virtual
  - curl -s https://get.docker.com/ | sh
  - sudo usermod -aG docker $USER
  - sudo chown -R $USER /etc/docker
  - sudo service docker restart
  - lsmod
  - sudo docker info

script:
  - wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.7.42/cslang-builder.zip
  - unzip cslang-builder.zip -d cslang-builder
  - chmod +x cslang-builder/bin/cslang-builder
  - docker run --privileged -d -p 4444 -p 49153:22 -e PORT=4444 --name docker_host_ssh orius123/dind-ssh &&
      ./cslang-builder/bin/cslang-builder -ts ${SUITE},\!default -cov
