language: java

sudo: required

before_install: |
  # needed for the UML container
  sudo apt-get install -qq -y slirp aufs-tools cgroup-lite

  # prepare docker dir for aufs mount
  sudo mkdir -p /var/lib/docker

  # download usermode linux kernel for docker
  curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
  chmod +x linux

  # download docker
  curl -sLo docker \
    https://get.docker.io/builds/Linux/x86_64/docker-1.3.2
  chmod +x docker

script:
  - docker run --privileged -d -p 4444 -p 49153:22 -e PORT=4444 --name docker_host_ssh orius123/dind-ssh
  - docker port docker_host_ssh 22
  - docker ps -a
  - wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.7.28/cslang-builder.zip
  - unzip cslang-builder.zip -d cslang-builder
  - chmod +x cslang-builder/bin/cslang-builder
  - ./cslang-builder/bin/cslang-builder -ts docker